### ISSUE TITLE
Ignoring cache directories

### ISSUE THREAD

**Issue by arseniiv** [SlavaCat118/vitfov#2]
You probably want to add a `.gitignore` file at the repo’s root directory and paste a single line
```
__pycache__/
```
in there, for git to not stage (and commit) contents of all `__pycache__` directories, and themselves. If you’re going to use tools like pytest or mypy, there go lines like
```
.pytest_cache/
.mypy_cache/
```
which add ignoring their caches.

**Comment by SlavaCat118** [comment]
Thanks, will do
